# Generated by Django 5.0 on 2024-01-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('train_no', models.IntegerField()),
                ('start', models.CharField(max_length=50)),
                ('end', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('timing', models.TimeField(default=False)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
    ]
